casbin/casbin-oa

- README.md
> fix: Add README.md

- web/src/RoundEditPage.js
you can choose a round‘s program when edit
> feat: Rounds can update program

- conf/app.conf
- controllers/report.go
- main.go
- object/event.go
- object/org_repositories.go
- object/report.go
- util/githubAPI.go
- web/src/RankingPage.js
- web/src/backend/ReportBackend.js
Fix some bug and change code style
> Feat: Fix some bug and change code style

- controllers/report.go
- object/event.go
- object/report.go
- web/src/RankingPage.js
Fix the bug that if you click the button 'Update Events',the report text will constantly add. what's more, the weekly template will generate  from backend for the function updating weekly report regularly in the backend
> fix: Generate template from backend

- web/src/App.js
- web/src/Conf.js
Deployed at: https://oa.chromium.link
> feat: add Casnode embed plguin

- web/src/IssueEditPage.js
fix issueEditPage problem and improve UI
> feat: Fix issueEditPage problem

- object/org_repositories.go
fix the bug that you can only get 100 repositories at most
> fix: Fix get repositories from github

- object/report.go
- object/round.go
fix the problem that the regular updating doesn't work
> fix: Fix regular problem

- controllers/webhook.go
- util/githubAPI.go
Improve the code about github API
> feat: Improve the code about github API

- controllers/webhook.go
- go.mod
- go.sum
- main.go
- object/event.go
- object/issue.go
- object/org_repositories.go
- object/org_webhook.go
- object/payLoad.go
- util/githubAPI.go
- util/webhookAPI.go
regular redeliver the unsuccessful webhook
> feat: Regularly redeliver the unsuccessful webhook

- controllers/webhook.go
> feat: Improve the webhook code

- object/report.go
Fix problem if no github event, it will 'Get Empty'
> fix: Fix 'Get Empty' problem

- util/githubAPI.go
Add 'implement' to enhancement words
> feat: Add 'implement' to enhancement words

- util/githubAPI.go
feat: Add 'update' to enhancement words
> feat: Add 'update' to enhancement words

- controllers/webhook.go
- object/issue.go
- routers/router.go
- util/githubAPI.go
- web/src/IssueEditPage.js
- web/src/IssueListPage.js
Signed-off-by: MRGUOKING 420919469@qq.com
feat: Assign someone as code reviewers when a pull request open
Signed-off-by: MRGUOKING 420919469@qq.com
> feat: Add Code Reviewe 

- controllers/webhook.go
- util/githubAPI.go
> fix: Fix set Reviewers problem

- controllers/webhook.go
Remove pull request author from reviewers
> fix: Remove pull request author from reviewers

- controllers/webhook.go
It will not execute webhook when no reviewer
> fix: It will not execute webhook when no reviewer

- util/githubAPI.go
Improve set label when issue open
> feat: Improve set label when issue open

- README.md
> fix:lost of casdoor part
